version: '2'

services:
  redis:
    restart: always
    image: redis:alpine
  
  nginx:
    restart: always
    image: nginx:alpine
    depends_on:
      - shared
    ports:
      - "8080:80"
    volumes:
      - ./volumes/shared:/var/www/:Z  
      - ./volumes/nginx/log:/var/log/nginx:Z
      - ./volumes/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:Z
    env_file: ./volumes/nginx/.env

  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - ./volumes/postgres/data:/var/lib/postgres/data:Z
    env_file: ./volumes/postgres/.env

  shared:
    restart: always
    image: shared:standard
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "5005:5005"  
      - "9009:9009"  
    volumes:
      - ./volumes/shared:/app:Z
      - ./volumes/shared/log:/var/log/:Z
      - ./volumes/shared/env.docker:/app/.env:Z
      - ./volumes/shared/etc/supervisor:/etc/supervisor:Z
    env_file: ./volumes/shared/env.docker
    command: /supervisor.sh
