version: '2'

services:
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./volumes/redis/config:/root/.redis:Z  

  rabbitmq:
    restart: always
    image: rabbitmq:alpine
    volumes:
      - ./volumes/rabbitmq/conf:/etc/rabbitmq/rabbitmq.config:Z  
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq:Z

  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./volumes/minio/conf:/root/.minio:Z  
      - ./volumes/minio/data:/data:Z

  thumbor:
    restart: always
    image: apsl/thumbor
    ports:
      - "3000:80"
    volumes:
      - ./volumes/thumbor/thumbor.conf:/usr/src/app/thumbor.conf.tpl:Z
    env_file:
      - env.thumbor

  elastic:
    restart: always
    image: elasticsearch:5.6-alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/elastic/conf:/usr/share/elasticsearch/config:Z
      - ./volumes/elastic/data:/usr/share/elasticsearch/data:Z
    environment:
      - transport.host=0.0.0.0 
      - discovery.zen.minimum_master_nodes=1
      - -Des.node.name="TestNode"

  nginx:
    restart: always
    image: nginx:alpine
    depends_on:
      - django
    ports:
      - "8080:80"
    volumes:
      - ./volumes/app:/app:Z  
      - ./volumes/log:/var/log/nginx:Z
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:Z
    env_file: ./volumes/app/env.docker

  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql:Z
    env_file: ./volumes/app/env.docker

  django:
    restart: always
    image: django:shared
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "5005:5005"  
      - "9009:9009"  
    volumes:
      - ./volumes/django:/app:Z
      - ./volumes/django/log:/var/log/:Z
      - ./volumes/django/env.docker:/app/.env:Z
      - ./volumes/django/etc/supervisor:/etc/supervisor:Z
    env_file: ./volumes/django/env.docker
    command: /supervisor.sh
